export enum EducationDegree {
  SECONDARY = "SECONDARY",
  HIGH_SCHOOL = "HIGH_SCHOOL",
  ASSOCIATE = "ASSOCIATE",
  BACHELOR = "BACHELOR",
  MASTER = "MASTER",
  DOCTORATE = "DOCTORATE",
  MBA = "MBA",
  CERTIFICATE = "CERTIFICATE",
  OTHER = "OTHER",
}
