export enum LanguageProficiency {
  ELEMENTARY = "ELEMENTARY",
  ADVANCED = "ADVANCED",
  PROFESSIONAL = "PROFESSIONAL",
  FULL_PROFESSIONAL = "FULL_PROFESSIONAL",
  NATIVE_OR_BILINGUAL = "NATIVE_OR_BILINGUAL",
}
