export enum NotificationType {
  POST_LIKE = "POST_LIKE",
  POST_COMMENT = "POST_COMMENT",
  POST_REPOST = "POST_REPOST",
  COMMENT_REPLY = "COMMENT_REPLY",
  CONNECTION_REQUEST = "CONNECTION_REQUEST",
  CONNECTION_ACCEPTED = "CONNECTION_ACCEPTED",
  PROFILE_VIEW = "PROFILE_VIEW",
  NEW_FOLLOWER = "NEW_FOLLOWER",
  BADGE_EARNED = "BADGE_EARNED",
  SKILL_ENDORSED = "SKILL_ENDORSED",
  JOB_APPLICATION_RECEIVED = "JOB_APPLICATION_RECEIVED",
  JOB_APPLICATION_STATUS_CHANGED = "JOB_APPLICATION_STATUS_CHANGED",
}
