export enum NotificationType {
  POST_LIKE = "POST_LIKE",
  POST_COMMENT = "POST_COMMENT",
  POST_REPOST = "POST_REPOST",
  CONNECTION_REQUEST = "CONNECTION_REQUEST",
  CONNECTION_ACCEPTED = "CONNECTION_ACCEPTED",
  PROFILE_VIEW = "PROFILE_VIEW",
}
